### ISSUE TITLE
Keyword-get in threading macro does not work

### ISSUE THREAD

**Issue by mhuebert** [athos/kitchen-async#3] opened 2019-02-11 11:58 UTC
First off, thank you for this library - I am finding it to be very useful!

I think I've found a bug with using plain keywords in the `->` threading macro.

Using a plain keyword, the result is passed through unchanged:

```
(p/-> (new js/Promise (fn [resolve reject]
                        (resolve {:x 10})))
      :x
      (print))

=>  {:x 10}
    ^ incorrect
```
But if we use `(get _ :kw)`, the correct result is returned:
```
(p/-> (new js/Promise (fn [resolve reject]
                        (resolve {:x 10})))
      (get :x)
      (print))

=> 10
   ^ correct
```

**Comment by athos** [comment] 2019-02-11 20:19
Hi, @mhuebert!

Thanks for reporting the issue. I will look into it soon 😃

**Comment by athos** [comment] 2019-02-12 15:42
Hi, thanks again for reporting the issue!

After digging into this, it turns out that the root cause of it is that `p/then` doesn't handle keywords correctly as its callback:

```clojure
(-> (p/resolve {:x 10}) (p/then :x) (p/then prn))
;=> {:x 10}
```

The commit b161e4fc6051208b8bcb1c5ad4d2083815c26cb1 fixes the glitch (and I've checked all the additional tests pass locally), but I'm running into another CI trouble, so it would take a little more to publish a fixed SNAPSHOT release.

Or if you're using Clojure CLI, you could try the fixed version right now by specifying the commit SHA directly in your deps.edn.

**Comment by athos** [comment] 2019-02-19 14:45
@mhuebert Just fixed the CI issue and released a new SNAPSHOT 👍Give it a shot, please.

**Comment by athos** [comment] 2019-02-20 23:18
I'm closing the issue.

**Closed by athos** 2019-02-20 23:18 UTC

**Comment by mhuebert** [comment] 2019-02-28 11:32
@athos thanks! this works great. apologies for the delay, had some time away from this project.
